#!/usr/bin/env bash
# Shared helpers for the Navin W03 isolated acceptance environment.
# This file is sourced by the other scripts; it must not perform side effects
# beyond loading configuration and defining functions.
set -euo pipefail

ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$ENV_DIR/../../.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/compose.acceptance.yaml"
ACCEPTANCE_ENV="$ENV_DIR/acceptance.env"
LIB_DIR="$ENV_DIR/lib"
PROBE_DIR="$ENV_DIR/probe"

GENERATED_DIR="$ENV_DIR/generated"
STATE_DIR="$GENERATED_DIR/state"
EVIDENCE_ROOT="$GENERATED_DIR/evidence"
TLS_DIR="$GENERATED_DIR/tls"
CREDENTIALS_FILE="$GENERATED_DIR/credentials.env"
MAILBOX_CREDENTIALS_FILE="$GENERATED_DIR/mailbox-credentials.env"

# Load the (non-secret) acceptance configuration.
# shellcheck disable=SC1090
set -a; source "$ACCEPTANCE_ENV"; set +a

COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-navin-acceptance}"
NETWORK_NAME="${NAVIN_ACCEPTANCE_NETWORK:-navin-acceptance}"
DOMAIN="${NAVIN_ACCEPTANCE_DOMAIN:-company.test}"
MAIL_HOSTNAME="${NAVIN_ACCEPTANCE_MAIL_HOSTNAME:-mail.company.test}"
ALICE_ADDRESS="${NAVIN_ACCEPTANCE_ALICE:-alice}@$DOMAIN"
BOB_ADDRESS="${NAVIN_ACCEPTANCE_BOB:-bob}@$DOMAIN"
ALIAS_ADDRESS="${NAVIN_ACCEPTANCE_ALIAS:-team}@$DOMAIN"

SMTP_PORT="${NAVIN_ACCEPTANCE_SMTP_PORT:-10025}"
SUBMISSION_PORT="${NAVIN_ACCEPTANCE_SUBMISSION_PORT:-10587}"
IMAP_PORT="${NAVIN_ACCEPTANCE_IMAP_PORT:-10143}"
IMAPS_PORT="${NAVIN_ACCEPTANCE_IMAPS_PORT:-10993}"
HTTP_PORT="${NAVIN_ACCEPTANCE_HTTP_PORT:-18080}"
READY_TIMEOUT="${NAVIN_ACCEPTANCE_READY_TIMEOUT:-240}"

STALWART_IMAGE="${NAVIN_ACCEPTANCE_STALWART_IMAGE}"
STALWART_DIGEST="${NAVIN_ACCEPTANCE_STALWART_DIGEST}"
CLI_IMAGE="${NAVIN_ACCEPTANCE_CLI_IMAGE}"
CLI_DIGEST="${NAVIN_ACCEPTANCE_CLI_DIGEST}"

# Production identifiers that must never appear in this environment.
PRODUCTION_DOMAIN="production.example.invalid"
PRODUCTION_MAIL_HOSTNAME="mail.production.example.invalid"
PRODUCTION_WEBMAIL_HOSTNAME="webmail.production.example.invalid"
PRODUCTION_CONTAINER_NAMES=("navin-mail-stalwart" "navin-mail-snappymail")
PRODUCTION_PORTS=(25 465 587 993 8082 8888 443 80)

info() { printf '[INFO] %s\n' "$*"; }
pass() { printf '[ OK ] %s\n' "$*"; }
warn() { printf '[WARN] %s\n' "$*" >&2; }
fail() { printf '[FAIL] %s\n' "$*" >&2; exit 1; }

require_docker() {
  command -v docker >/dev/null 2>&1 || fail "docker CLI not found; W03 acceptance requires a Docker runtime"
  docker info >/dev/null 2>&1 || fail "Docker daemon is not reachable; start Docker and retry"
  docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
}

# Run docker compose against the acceptance file only. The production `.env`
# is never passed; interpolation uses acceptance.env exclusively.
compose() {
  ( cd "$REPO_ROOT" && docker compose \
      --project-name "$COMPOSE_PROJECT_NAME" \
      --project-directory "$REPO_ROOT" \
      --env-file "$ACCEPTANCE_ENV" \
      -f "$COMPOSE_FILE" "$@" )
}

load_credentials() {
  [[ -f "$CREDENTIALS_FILE" ]] || fail "Missing $CREDENTIALS_FILE (generated by seed.sh)"
  local mode
  mode="$(stat -c '%a' "$CREDENTIALS_FILE" 2>/dev/null || true)"
  [[ "$mode" == "600" ]] || fail "$CREDENTIALS_FILE must have mode 600 (current: ${mode:-unknown})"
  set -a
  # shellcheck disable=SC1090
  source "$CREDENTIALS_FILE"
  set +a
}

load_mailbox_credentials() {
  [[ -f "$MAILBOX_CREDENTIALS_FILE" ]] || fail "Missing $MAILBOX_CREDENTIALS_FILE (run seed.sh first)"
  local mode
  mode="$(stat -c '%a' "$MAILBOX_CREDENTIALS_FILE" 2>/dev/null || true)"
  [[ "$mode" == "600" ]] || fail "$MAILBOX_CREDENTIALS_FILE must have mode 600 (current: ${mode:-unknown})"
  set -a
  # shellcheck disable=SC1090
  source "$MAILBOX_CREDENTIALS_FILE"
  set +a
}

# --- Credential capture safety ------------------------------------------------
# A command substitution that carries a generated credential must receive
# exactly one non-empty token. Any extra line (for example a human status
# message) or embedded whitespace is a hard failure so invalid credentials are
# never written to disk.
require_one_token() {
  local label="$1" value="$2" pattern="${3:-}"
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || fail "$label capture contained a line break"
  [[ -n "$value" ]] || fail "$label capture was empty"
  [[ "$value" != *[[:space:]]* ]] || fail "$label capture contained whitespace"
  if [[ -n "$pattern" && ! "$value" =~ $pattern ]]; then
    fail "$label capture did not match the expected format"
  fi
}

# Parse a single "<address><TAB><password>" credential line and print the
# password. Fails closed on multiline output, a missing separator or a password
# that is not one non-empty alphanumeric token.
parse_credential_line() {
  local label="$1" line="$2" password
  [[ "$line" != *$'\n'* && "$line" != *$'\r'* ]] || fail "$label credential output was not a single line"
  [[ "$line" == *$'\t'* ]] || fail "$label credential output had no tab separator"
  password="${line#*$'\t'}"
  require_one_token "$label password" "$password" '^[A-Za-z0-9]{24}$'
  printf '%s' "$password"
}

# Run the pinned Stalwart CLI image on the isolated acceptance network.
stalwart_cli() {
  local -a credential_args=()
  if [[ -f "$CREDENTIALS_FILE" ]]; then
    load_credentials
    credential_args=(-e STALWART_USER -e STALWART_PASSWORD)
  fi
  docker run --rm -i --network "$NETWORK_NAME" \
    -e STALWART_URL="${STALWART_URL:-http://stalwart:8080}" \
    "${credential_args[@]}" \
    "$CLI_IMAGE" "$@"
}

# Normalize Stalwart CLI JSON output and extract fields without printing secrets.
stalwart_json() {
  python3 "$LIB_DIR/stalwart_json.py" "$@"
}

now_utc() { date -u +%Y-%m-%dT%H:%M:%SZ; }
